name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_REPO_NAME: "/ignite-call"
    steps:
    - uses: actions/ignite-call
      with:
        node-version: 12
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: touch ./out/.nojekyll

    - name: Deploy 🚀
      uses: GedioneSOuza/ignite-call
      with:
        folder: out